# Plugin information
plugin:
    name: Feedback Plugin
    description: Feedback plugin for OctoberCMS
    icon: icon-comment-o
    author: AvaloniumTeam
    homepage: https://github.com/avalonium/feedback-plugin

# Plugin navigation
navigation:
    feedback:
        label: Feedback
        url: avalonium/feedback/requests
        icon: icon-comment-o
        iconSvg: plugins/avalonium/feedback/assets/images/plugin-icon.svg
        sideMenu:
            requests:
                label: Requests
                url: avalonium/feedback/requests
                icon: icon-comment-o
                counter: \Avalonium\Feedback\Models\Request::countNewRequests
                counterLabel: New Requests

# Plugin permissions
permissions:
    avalonium.feedback.requests:
        tab: Feedback plugin
        label: Access to Requests

# Plugin settings
settings:
    settings:
        label: Feedback Settings
        description: Manage feedback settings
        category: Avalonium
        icon: icon-comment-o
        class: Avalonium\Feedback\Models\Settings
