# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Request

# Model Form Field configuration
form: $/avalonium/feedback/models/request/fields.yaml

# Model Class name
modelClass: Avalonium\Feedback\Models\Request

# Default redirect location
defaultRedirect: avalonium/feedback/requests

# Preview page
preview:
    title: backend::lang.form.preview_title
